plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'com.google.android.gms.oss-licenses-plugin'
}

android {
    namespace 'com.yjy.forestory'
    compileSdk 34

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }

    configurations.all {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }

    defaultConfig {
        applicationId "com.yjy.forestory"
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName "1.2.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        dataBinding = true
        viewBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

// Allow references to generated code
kapt {
    correctErrorTypes true
}

dependencies {
    // Paging
    def paging_version = "3.1.1"
    implementation "androidx.paging:paging-runtime:$paging_version"
    implementation "androidx.paging:paging-compose:1.0.0-alpha18"

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // OkHttp3
    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'

    // RoomDB
    def room_version = "2.5.0"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-paging:$room_version"

    // Hilt
    implementation "com.google.dagger:hilt-android:2.44"
    kapt "com.google.dagger:hilt-compiler:2.44"
    implementation 'androidx.hilt:hilt-work:1.0.0'
    kapt 'androidx.hilt:hilt-compiler:1.0.0'

    // Google Drive Api
    implementation 'com.google.android.gms:play-services-auth:20.6.0'
    implementation 'com.google.api-client:google-api-client-android:1.23.0'
    implementation 'com.google.api-client:google-api-client-gson:1.23.0'
    implementation 'com.google.apis:google-api-services-drive:v3-rev136-1.25.0'

    implementation 'com.google.android.gms:play-services-ads:22.2.0' // 애드몹
    implementation 'com.android.billingclient:billing:6.0.1' // 구글 결제
    implementation "androidx.biometric:biometric:1.2.0-alpha05" // 생체 인증
    implementation 'androidx.core:core-splashscreen:1.0.0-alpha01' // 스플래시
    implementation "androidx.work:work-runtime-ktx:2.8.1" // WorkManager
    implementation 'androidx.core:core-ktx:1.10.1' // Notification
    implementation 'com.google.android.gms:play-services-oss-licenses:17.0.1' // 오픈소스 표기
    implementation 'com.github.chrisbanes:PhotoView:2.3.0' // 이미지 확대 등 자세히보기
    implementation 'de.hdodenhof:circleimageview:3.1.0' // 원형 imageView
    implementation "androidx.datastore:datastore-preferences:1.0.0" // DataStore
    debugImplementation 'com.amitshekhar.android:debug-db:1.0.6' // RoomDB 데이터베이스 디버그용 시각화
    implementation 'com.google.code.gson:gson:2.10.1' // JSON <-> 자바오브젝트 직렬화 및 역직렬화
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0' // 사진 Crop
    implementation 'io.github.muddz:styleabletoast:2.4.0' // 커스텀 토스트
    implementation 'com.github.logansdk:logan-permission:0.9.26' // 권한 요청
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}